#!/bin/bash

echo "=== Manual Test Results ==="
echo ""
echo "Based on the implementation, here's what the endpoints should do:"
echo ""

echo "1. POST /api/v1/solicitud"
echo "   Request:"
echo "   {"
echo "     \"user_id\": \"1234567\","
echo "     \"amount\": 1000000.00,"
echo "     \"term_months\": 12,"
echo "     \"loan_type\": \"BUSINESS\""
echo "   }"
echo ""
echo "   Expected Response (201 Created):"
echo "   {"
echo "     \"id\": \"generated-uuid\","
echo "     \"status\": \"PENDING_REVIEW\","
echo "     \"user_id\": \"1234567\","
echo "     \"amount\": 1000000.00,"
echo "     \"term_months\": 12,"
echo "     \"loan_type\": \"BUSINESS\","
echo "     \"created_at\": \"2025-09-08T19:00:00Z\""
echo "   }"
echo ""

echo "2. GET /api/v1/solicitud (requires JWT with 'Asesor' role)"
echo "   Without JWT: 401 Unauthorized"
echo "   With invalid role: 403 Forbidden"
echo "   With valid JWT (Asesor role):"
echo "   {"
echo "     \"content\": ["
echo "       {"
echo "         \"id\": \"1\","
echo "         \"monto\": 50000,"
echo "         \"plazo\": 24,"
echo "         \"email\": \"juan@example.com\","
echo "         \"nombre\": \"Juan Pérez\","
echo "         \"tipo_prestamo\": \"PERSONAL\","
echo "         \"tasa_interes\": 12.5,"
echo "         \"estado_solicitud\": \"PENDING_REVIEW\","
echo "         \"salario_base\": 3000000,"
echo "         \"monto_mensual_solicitud\": 2500"
echo "       }"
echo "     ],"
echo "     \"page\": 0,"
echo "     \"size\": 10,"
echo "     \"total_elements\": 2,"
echo "     \"total_pages\": 1"
echo "   }"
echo ""

echo "3. Validation Errors (400 Bad Request):"
echo "   - Missing user_id: 'customerDocument is required'"
echo "   - Invalid amount: 'amount must be positive'"
echo "   - Invalid term_months: 'termMonths must be positive'"
echo "   - Invalid loan_type: 'loanType is invalid'"
echo ""

echo "4. Available Loan Types:"
echo "   - PERSONAL"
echo "   - MORTGAGE"
echo "   - AUTO"
echo "   - BUSINESS"
echo ""

echo "5. JWT Token Example (for testing GET endpoint):"
echo "   Header: Authorization: Bearer <jwt-token>"
echo "   Token should contain: {\"role\": \"Asesor\"}"
echo ""

echo "6. Swagger UI: http://localhost:8082/swagger-ui.html"
echo "7. Health Check: http://localhost:8082/actuator/health"