server:
  port: 8082

spring:
  application:
    name: "ms-solicitudes"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crediya
    username: yulianaarangolopez
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    include: null
  jackson:

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

jwt:
  secret: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQVNFU09SIiwidXNlcklkIjoiZDgwMDk2MmItYjczYi00OGUyLTk3MzgtNTBjMDQzYjdhNzFjIiwiZW1haWwiOiJudWV2b0BnbWFpbC5jb20iLCJzdWIiOiJudWV2b0BnbWFpbC5jb20iLCJpYXQiOjE3NTczODE3MjAsImV4cCI6MTc1NzQ2ODEyMH0.slQOQXKEIBYfF9EIBCHrL1UWVUEaqDdkbRqqVNtnSEY"

app:
  mock-mode: false

adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya
    schema: public
    username: yulianaarangolopez
    password: ""
    initial-size: 2
    max-size: 10
    max-idle-time: 30s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true