server:
  port: 8082

spring:
  application:
    name: "ms-solicitudes"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

app:
  mock-mode: true

jwt:
  secret: "testSecretKeyForJwtTokenValidationThatIsLongEnough"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tryItOutEnabled: true