name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests and coverage
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2g"
        run: ./gradlew clean test jacocoTestReport jacocoTestCoverageVerification --no-daemon

      - name: Upload JaCoCo HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: |
            **/build/reports/jacoco/test/html
            build/reports/jacocoMergedReport/html

      - name: Upload Test results (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/build/test-results/test'
